// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CompareZones(arg1:string):Promise<Array<main.NPCDiffRow>>;

export function Connect(arg1:main.ConnectionConfig,arg2:boolean):Promise<void>;

export function GetNPCsForZone(arg1:string,arg2:boolean):Promise<Array<main.NPC>>;

export function GetZones():Promise<Array<main.Zone>>;

export function LoadConfig():Promise<main.Config>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function Sync(arg1:main.SyncOptions):Promise<main.SyncResult>;
