// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompareGrids(arg1) {
  return window['go']['main']['App']['CompareGrids'](arg1);
}

export function CompareNPCFaction(arg1, arg2) {
  return window['go']['main']['App']['CompareNPCFaction'](arg1, arg2);
}

export function CompareSpawnGroups(arg1, arg2) {
  return window['go']['main']['App']['CompareSpawnGroups'](arg1, arg2);
}

export function CompareSpawns(arg1, arg2) {
  return window['go']['main']['App']['CompareSpawns'](arg1, arg2);
}

export function CompareZones(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompareZones'](arg1, arg2, arg3);
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function GetNPCsForZone(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetNPCsForZone'](arg1, arg2, arg3, arg4);
}

export function GetZones() {
  return window['go']['main']['App']['GetZones']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadTODOItems() {
  return window['go']['main']['App']['LoadTODOItems']();
}

export function PickPrivateKeyFile() {
  return window['go']['main']['App']['PickPrivateKeyFile']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetTODOItemDismissed(arg1, arg2) {
  return window['go']['main']['App']['SetTODOItemDismissed'](arg1, arg2);
}

export function Sync(arg1) {
  return window['go']['main']['App']['Sync'](arg1);
}

export function SyncGrids(arg1) {
  return window['go']['main']['App']['SyncGrids'](arg1);
}

export function SyncSpawnGroup(arg1) {
  return window['go']['main']['App']['SyncSpawnGroup'](arg1);
}

export function SyncSpawnPoints(arg1) {
  return window['go']['main']['App']['SyncSpawnPoints'](arg1);
}
