// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.ConnectionConfig,arg2:boolean):Promise<void>;

export function GetNPCsForZone(arg1:string):Promise<Array<main.NPC>>;

export function GetZones():Promise<Array<main.Zone>>;
