// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CompareGrids(arg1:number):Promise<Array<main.GridDiffRow>>;

export function CompareNPCFaction(arg1:number,arg2:number):Promise<main.NPCFactionComparison>;

export function CompareNPCLoot(arg1:number,arg2:number):Promise<main.NPCLootComparison>;

export function CompareNPCMerchant(arg1:number,arg2:number):Promise<main.NPCMerchantComparison>;

export function CompareNPCSpells(arg1:number,arg2:number):Promise<main.NPCSpellsComparison>;

export function CompareSpawnGroups(arg1:string,arg2:number):Promise<Array<main.SpawnGroupDiffRow>>;

export function CompareSpawns(arg1:string,arg2:number,arg3:number):Promise<Array<main.SpawnDiffRow>>;

export function CompareZones(arg1:string,arg2:number,arg3:number):Promise<Array<main.NPCDiffRow>>;

export function Connect(arg1:main.ConnectionConfig,arg2:boolean):Promise<void>;

export function GetLootTable(arg1:boolean,arg2:number):Promise<main.LootTable>;

export function GetNPCsForZone(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<Array<main.NPC>>;

export function GetZones():Promise<Array<main.Zone>>;

export function LoadConfig():Promise<main.Config>;

export function LoadTODOItems():Promise<Array<main.TODOItem>>;

export function PickPrivateKeyFile():Promise<string>;

export function RelocateSpawnGroup(arg1:main.RelocateSpawnGroupOptions):Promise<main.RelocateSpawnGroupResult>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SetTODOItemDismissed(arg1:number,arg2:boolean):Promise<void>;

export function Sync(arg1:main.SyncOptions):Promise<main.SyncResult>;

export function SyncGrids(arg1:main.SyncGridsOptions):Promise<main.SyncGridsResult>;

export function SyncSpawnGroup(arg1:main.SyncSpawnGroupOptions):Promise<main.SpawnGroupSyncResult>;

export function SyncSpawnPoints(arg1:main.SpawnSyncOptions):Promise<main.SpawnSyncResult>;
